# Generated by Django 5.1.3 on 2024-12-03 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airlines_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="reservation_code",
            field=models.CharField(default="821DBBC7EA", max_length=10, unique=True),
        ),
    ]
